# Generated by Django 2.0.4 on 2018-05-01 01:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('short_description', models.CharField(max_length=50)),
                ('long_description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='BalanceTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_value', models.FloatField()),
                ('qr_code', models.UUIDField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.Account')),
            ],
        ),
        migrations.CreateModel(
            name='BalanceTicketTrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_bal', models.FloatField()),
                ('post_bal', models.FloatField()),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketing.BalanceTicket')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=10)),
                ('token', models.CharField(max_length=100)),
                ('expiry', models.DateField()),
                ('name', models.CharField(max_length=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
                ('title', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=400)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketing.Account')),
                ('bt_trip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketing.BalanceTicketTrip')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pin', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PushNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=162)),
                ('expire', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.Account')),
            ],
        ),
        migrations.CreateModel(
            name='RideTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_rides', models.IntegerField()),
                ('initial_value', models.IntegerField()),
                ('qr_code', models.UUIDField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='RideTicketTrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_bal', models.IntegerField()),
                ('post_bal', models.IntegerField()),
                ('rt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketing.RideTicket')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=90)),
                ('cost', models.FloatField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='TopUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_bal', models.FloatField()),
                ('post_bal', models.FloatField()),
                ('amount', models.FloatField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.Account')),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketing.BalanceTicket')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketing.Card')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketing.Driver')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketing.Route')),
            ],
        ),
        migrations.AddField(
            model_name='ridetickettrip',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketing.Trip'),
        ),
        migrations.AddField(
            model_name='rideticket',
            name='valid_for',
            field=models.ManyToManyField(to='ticketing.Route'),
        ),
        migrations.AddField(
            model_name='balancetickettrip',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketing.Trip'),
        ),
    ]
