# Generated by Django 2.0.4 on 2018-05-02 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField()),
                ('title', models.CharField(max_length=25)),
                ('short_description', models.CharField(max_length=50)),
                ('long_description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Announcements',
        ),
    ]
