# Generated by Django 2.0.4 on 2018-05-08 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0002_auto_20180502_0339'),
    ]

    operations = [
        migrations.AddField(
            model_name='rideticket',
            name='short_name',
            field=models.CharField(default='blah', max_length=10),
            preserve_default=False,
        ),
    ]
