# Generated by Django 2.0.4 on 2018-05-15 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0003_auto_20180515_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushnotification',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_tokens', to='ticketing.Account'),
        ),
    ]
