# Generated by Django 2.0.4 on 2018-07-17 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0003_rideticket_short_name'),
        ('ticketing', '0004_auto_20180515_0313'),
    ]

    operations = [
    ]
