# Generated by Django 2.0.4 on 2018-07-31 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0006_auto_20180731_0015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balanceticket',
            old_name='qr_code',
            new_name='qr_code_id',
        ),
    ]
