# Generated by Django 2.0.4 on 2018-08-07 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0007_auto_20180731_0335'),
        ('ticketing', '0005_auto_20180731_0221'),
    ]

    operations = [
    ]
