# Generated by Django 2.0.4 on 2018-09-18 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0008_merge_20180807_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='end',
            field=models.DateTimeField(null=True),
        ),
    ]
