language: python

python:
  - "3.6"

notifications:
  email: false

install:
  - pip install pycodestyle
  - pip install -r requirements.txt

script:
  - pycodestyle --exclude='*migrations/*' ticketing/
  - python3 manage.py test