language: python
python:
- '3.6'
notifications:
  email: false
  slack:
    secure: XZF5E4mc9l9b9borXlmoGOdW5dVFzJRkUZEJU3Kz/CNv/5wQiB+pz0oeYUzGvzB+DCMscuEuGTGry5ApPC4pWHnDTd1T/XrofDd+9Fd2dCleoqLSUfbFRYlNwLCOoZV9QhyIq8HNiDmW1xMPBI2qSOy6L3uL3PJeZVu+67ov88j/MXV4bWYbBViqgqCX2mzGdsFV6twTawSUoCJKmMV1D6ON7aZWjIJHQEH9iz0xDIPs4G4/tVHwsIlv7y+RvTFAeEQCk+DBTjt2vmZn7vfnlRPI2/OVHsvH/n2FUsTF18OU3HQyFDDHwK7sXFZ47sECA+SKlKcI5AEJ9wkGtmqGLxCuYDJjNKNiuR1TlK8vJIW3mdFNp9KQoAfIBfQvYLVWI6HEPaMRy+6I937uZJL6N8bQ55tNgf4mgrSCXhk/0ctXkf5jjob9amIkshjShaqtcpF1lL8djZxRFTa+po68ts4v/HWMeZx0IVlUww4Dc13+A5+/FkjAkg0Qmw1Ec0E7LLKHfOYoktJ7+xxc6/cml1okEoUjzq5/0u/6nDjcoNQAdI/qBz6DnIvY2e7etjLqRU35NOpcp0j9shyPa/C96Zw0c2lGVuuQJlY1nt6l2wjQVSzVTC/pl9sPSXJWyCrtPxpwfgSMlj9tZ8GTiW/qPCsMAJ/jG+2/uIv1gN5ybP8=
install:
- pip install pycodestyle
- pip install -r requirements.txt
script:
- pycodestyle --exclude='*migrations/*' ticketing/
- python3 manage.py test
env:
- PRIVATE_KEY="-----BEGIN RSA PRIVATE KEY----- MIIBOgIBAAJBALOBBafOYGgvdzx4O/9LIQZU9UEONqAEacNequPCXZL2XYgHRfAR
  exh5xSAahI3r2fpsn/kxzvq0Zot81/Zoe20CAwEAAQJAFpi1V4x5QmRHREt2cgrJ G3zyasAZTEeB8OAn7wf2s5st4vFCQqFGv99JwmvyGSCw/LWW546T95oOPOT8+x0S
  2QIhAN9IxbXskaud1sj+SP5lsLAcshQsPJdXx0IKp/b/AbpfAiEAzc4VhjYntCMB g75YLe+LlyxnVbXTSPIdbkOKKWNStbMCICYe8Ypm0lP/ha0ZJPMx/2GB9LFXAB1C
  okVXNmgID453AiBqOGBxmcfaOGsStQ5L/yPbzYYz/ZlkP9oiy+cmP2Yz8wIhAJD6 oj4alRlt640uUl3U5UMcUjQWrUxFavjqZqvjOAEQ
  -----END RSA PRIVATE KEY-----" PUBLIC_KEY="-----BEGIN RSA PUBLIC KEY----- MEgCQQCzgQWnzmBoL3c8eDv/SyEGVPVBDjagBGnDXqrjwl2S9l2IB0XwEXsYecUg
  GoSN69n6bJ/5Mc76tGaLfNf2aHttAgMBAAE= -----END RSA PUBLIC KEY-----"
deploy:
- provider: script
  script: bash scripts/dev_deploy.sh
  on:
    branch: dev